name: Matem치tica - Licenciatura
title: Matem치tica - Licenciatura
description: P치gina mantida pelos alunos de MAF 172 - Matem치tica Computacional
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
email: maf172@gmail.com
disqus_username: disqus_username
show_hero: true
